#!/usr/bin/env python3
"""
Generate audio narration from demo script using Edge TTS (free, no API key)
Install: pip install edge-tts
"""

import asyncio
import edge_tts

# Clean narration text - follows exact tab order (~3 minutes)
NARRATION = """
Managing cloud infrastructure shouldn't feel like firefighting.

Meet Cloud Ops Sentinel — an AI-powered cloud operations assistant that detects issues before they become problems, forecasts your costs, and fixes things automatically.

Let me walk you through the platform.

First, the Dashboard. This is your command center. At a glance, you see total instances, running services, health score, and daily costs. Everything updates in real-time with one click.

Next, Idle Resources. This is where we find money. The system automatically detects instances with low CPU and RAM utilization. Each one shows exactly how much you'd save by terminating it. In this example, over a hundred dollars in monthly savings.

Cost Forecast. Planning your budget? Select a month and get a prediction of your cloud spend. You see the confidence score, breakdown by tier, and risk factors that might affect your bill. No more surprise invoices.

Metrics and Anomalies. Select any service and instantly see CPU, RAM, latency, and error rates. Our AI-powered anomaly detection analyzes these metrics automatically. It catches issues, shows the severity, and recommends exactly what to do.

Service Control. When something needs a restart, you don't need to SSH anywhere. Select a service, click restart, and Cloud Ops Sentinel handles it through Modal or Blaxel backends. You get instant feedback — time taken and post-restart health.

Ops Report. Need to brief your team? Generate a comprehensive AI-powered report with one click. Health status, cost analysis, anomalies, and recommendations — all generated by SambaNova's large language model.

Ops Chat. Don't want to click around? Just ask in plain English. Type "show me idle instances" or "restart the web service" — the AI understands and executes the right MCP tools automatically.

Hygiene Score. One number — zero to one hundred — measuring overall infrastructure health. It weighs idle resources, anomalies, and service health into one actionable metric.

Auto-Remediation. This is autonomous mode. Toggle it on, and the system continuously monitors all services. When it detects a high or critical anomaly, it automatically restarts the service, verifies health, and logs the event. Right now our infrastructure is healthy, so no events yet. In production, this runs hands-free twenty-four seven.

Finally, Download Report. Click Preview Report to see the full report, then click the green download button to save it as a Markdown file.

Under the hood, Cloud Ops Sentinel integrates with six hackathon sponsors: Modal for compute, Hyperbolic for embeddings, Blaxel as alternative backend, SambaNova for LLM reports, HuggingFace for the UI, and LangChain for orchestration.

Six MCP tools. One unified interface. Zero complexity.

Cloud Ops Sentinel — because your infrastructure deserves an AI that actually watches your back.

Try it now on Hugging Face Spaces. Thanks for watching.
"""

async def generate_audio():
    # Good voice options:
    # en-US-GuyNeural - Professional male
    # en-US-ChristopherNeural - Warm male  
    # en-US-JennyNeural - Professional female
    # en-GB-RyanNeural - British male
    
    voice = "en-US-GuyNeural"
    output_file = "demo_narration.mp3"
    
    print(f"Generating audio with voice: {voice}")
    print(f"Output file: {output_file}")
    
    # Using pitch adjustment for better quality output
    communicate = edge_tts.Communicate(NARRATION, voice, rate="-5%", pitch="+0Hz")
    await communicate.save(output_file)
    
    print(f"✅ Audio saved to {output_file}")
    print("You can now use this in your video editor!")

if __name__ == "__main__":
    asyncio.run(generate_audio())
